# server.port: 配置Tomcat端口号
# server.servlet.context-path: 配置应用名
server:
  port: 8083
  servlet:
    context-path: /

# 静态资源映射
# spring.mvc.static-path-pattern: 相对路径
# spring.resources 或 spring.web.resources: 本地路径
# 配置数据源
# spring.datasource.* :配置数据源
spring:
  mvc:
    static-path-pattern: /pic/**
  web:
    resources:
      static-locations: file:d:/spring/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 43.138.55.158
    port: 6379
    lettuce:
      shutdown-timeout: 0


# 配置Mybatis
# mybatis.configuration.cache-enabled: 开启缓存
mybatis:
  configuration:
    cache-enabled: true
  # Sssd typeHandler 哦欸之
  type-handlers-package: com.cskaoyan.typehandler



# 配置自动分页
pagehelper:
  helper-dialect: mysql

# 配置日志
logging:
  level:
    com.cskaoyan.mapper: debug

# 配置异常日志路径
com:
  cskaoyan:
    logPath: D://log.txt


# sms
aliyun:
  accessKeyId: LTAI4Fr5gfYhcVjLMqeRGbuT
  accessKeySecret: IrkcHu6dZyrjPZRushgO76P5392HJ1
  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
  sms:
    signName: stone4j
    templateCode: SMS_173765187
